---
proxmox:
  hosts:
    saa1-ibiscloud:
      ansible_host: saa1-ibiscloud.netbird
    saa2-ibiscloud:
      ansible_host: saa2-ibiscloud.netbird

linux_server:
  hosts:
    netbird:
      ansible_host: netbird.netbird
    revproxy:
      ansible_host: revproxy.netbird
    webserver:
      ansible_host: webserver.netbird
    nextcloud:
      ansible_host: nextcloud.netbird
    dockerhost:
      ansible_host: dockerhost.netbird
    authentik:
      ansible_host: authentik.netbird
    vaultwarden:
      ansible_host: vaultwarden.netbird
    paperless-ngx:
      ansible_host: paperless-ngx.netbird

lxc_container:
  hosts:
    revproxy:
      ansible_host: revproxy.netbird

