---
common_packages:
  - sudo
  - curl
  - vim
  - git
  - htop

common_packages_linux:
  - software-properties-common
  - zip
  - unzip
  - p7zip-full

time_timezone: "Europe/Berlin"
time_ntp_packages:
  - ntpsec
  - ntpsec-ntpdate
time_ntp_server: "pool.ntp.org"
