---
- name: Set timezone
  community.general.timezone:
    name: "{{ time_timezone }}"

- name: Install NTPsec packages
  ansible.builtin.apt:
    name: "{{ time_ntp_packages }}"
    state: present
    update_cache: true

- name: Enable and start NTPsec service
  ansible.builtin.service:
    name: ntpsec
    state: started
    enabled: true

- name: Perform one-time NTP sync
  ansible.builtin.command:
    argv:
      - ntpdate
      - "-u"
      - "{{ time_ntp_server }}"
  register: linux_server_no_lxc_ntpdate_result
  changed_when: "'time stepped' in linux_server_no_lxc_ntpdate_result.stdout"
  failed_when: linux_server_no_lxc_ntpdate_result.rc != 0
